### PR TITLE
fix compilation error on FreeBSD 13 CURRENT

### PR DESCRIPTION
**Pull request by hxw**
sys/types.h is necessary for the u_int typedef

Signed-off-by: Christopher Hall <hsw@bitmark.com>

### CODE REVIEW

**Comment by hxw** [comment]
I also tested that this addition builds correctly on FreeBSD 12.1-RELEASE

**Comment by jsouthworth** [comment]
Thanks!
